import React from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy | Proventa Credit Intelligence',
  description: 'Proventa Privacy Policy — GDPR and PDPB compliant data handling practices.',
};

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'Inter, sans-serif' }}>
      {/* Header */}
      <header style={{ background: '#0B1F3A', padding: '1.25rem 2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', textDecoration: 'none' }}>
          <div style={{ width: '36px', height: '36px', background: 'linear-gradient(135deg, #2563EB, #7C3AED)', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 900, fontFamily: 'Outfit, sans-serif', fontSize: '1.1rem' }}>P</div>
          <span style={{ color: '#fff', fontFamily: 'Outfit, sans-serif', fontWeight: 800, fontSize: '1.2rem', letterSpacing: '-0.02em' }}>PROVENTA</span>
        </Link>
        <Link href="/" style={{ color: 'rgba(255,255,255,0.7)', textDecoration: 'none', fontSize: '0.875rem', fontWeight: 500 }}>
          ← Back to Home
        </Link>
      </header>

      {/* Main Content */}
      <main style={{ maxWidth: '820px', margin: '0 auto', padding: '3rem 2rem' }}>
        {/* Title */}
        <div style={{ marginBottom: '2.5rem' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'rgba(37,99,235,0.08)', border: '1px solid rgba(37,99,235,0.2)', borderRadius: '999px', padding: '0.3rem 0.9rem', marginBottom: '1rem' }}>
            <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#10B981', display: 'inline-block' }} />
            <span style={{ fontSize: '0.78rem', fontWeight: 700, color: '#2563EB', letterSpacing: '0.06em' }}>GDPR & PDPB COMPLIANT</span>
          </div>
          <h1 style={{ fontSize: '2.25rem', fontFamily: 'Outfit, sans-serif', fontWeight: 900, color: '#0B1F3A', marginBottom: '0.5rem', lineHeight: 1.2 }}>
            Privacy Policy
          </h1>
          <p style={{ color: '#6b7280', fontSize: '0.9rem' }}>
            <strong>Effective Date:</strong> January 1, 2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> January 1, 2025
          </p>
          <p style={{ color: '#374151', fontSize: '0.95rem', marginTop: '1rem', lineHeight: 1.7 }}>
            Proventa Technologies Private Limited ("Proventa", "we", "us", or "our") is committed to protecting your privacy and handling your personal and organizational data with the highest standards of security and transparency. This Privacy Policy explains how we collect, use, disclose, and safeguard information when you use the Proventa Credit Intelligence Platform.
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>
          {/* Section 1 */}
          <Section title="1. Data We Collect">
            <p>We collect the following categories of information to deliver our credit intelligence services:</p>
            <SubSection title="1.1 Account & Identity Data">
              <ul>
                <li>Full name, business email address, phone number</li>
                <li>Organization name, GST Identification Number (GSTIN), PAN</li>
                <li>Job title, department, and role within your organization</li>
                <li>Login credentials (passwords stored as Argon2id hashes — never in plaintext)</li>
              </ul>
            </SubSection>
            <SubSection title="1.2 Business & Financial Data">
              <ul>
                <li>Company financial information (annual revenue, turnover, employee count)</li>
                <li>Customer profiles and trade receivables data you upload</li>
                <li>Invoice records, payment histories, and aging data</li>
                <li>Credit assessments and risk scores generated by our platform</li>
                <li>Bank statement data (if uploaded for analysis — processed and not stored permanently)</li>
              </ul>
            </SubSection>
            <SubSection title="1.3 Technical & Usage Data">
              <ul>
                <li>IP address, device type, browser, and operating system</li>
                <li>Session tokens (stored as SHA-256 hashes in our database)</li>
                <li>Pages visited, features accessed, and time spent on platform</li>
                <li>API request logs for developer accounts</li>
              </ul>
            </SubSection>
            <SubSection title="1.4 Third-Party Data">
              <ul>
                <li>GSTIN lookup data from MasterGST / GST portal APIs</li>
                <li>Company data from MCA/ROC registries</li>
                <li>Payment processing data via Stripe (we never store full card numbers)</li>
              </ul>
            </SubSection>
          </Section>

          {/* Section 2 */}
          <Section title="2. How We Use Your Data">
            <p>We use the data collected for the following legitimate purposes:</p>
            <ul>
              <li><strong>Service Delivery:</strong> Generating credit assessments, risk scores, and financial forecasts</li>
              <li><strong>Account Management:</strong> Maintaining your account, billing, and subscription</li>
              <li><strong>Security & Fraud Prevention:</strong> Detecting and preventing unauthorized access, maintaining audit logs</li>
              <li><strong>AI/ML Model Improvement:</strong> Improving credit scoring models using anonymized, aggregated data only</li>
              <li><strong>Communications:</strong> Sending transactional emails, security alerts, and product updates (you may opt out of marketing)</li>
              <li><strong>Legal Compliance:</strong> Fulfilling obligations under Indian law (IT Act, 2000; PDPB; Companies Act)</li>
            </ul>
            <p style={{ marginTop: '1rem' }}>We do <strong>not</strong> sell your personal data to third parties. We do not use your financial data for advertising or profiling unrelated to our credit services.</p>
          </Section>

          {/* Section 3 */}
          <Section title="3. Data Sharing">
            <p>We share data only in the following limited circumstances:</p>
            <ul>
              <li><strong>Service Providers:</strong> Cloud infrastructure (AWS/Google Cloud), email delivery (SendGrid), payment processing (Stripe), AI APIs (Google Gemini) — all bound by data processing agreements</li>
              <li><strong>Regulatory Authorities:</strong> If required by law, court order, or government request under the IT Act, 2000 or applicable Indian law</li>
              <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or asset sale — with advance notice to users</li>
              <li><strong>Your Explicit Consent:</strong> Any sharing beyond the above requires your explicit, documented consent</li>
            </ul>
            <p style={{ marginTop: '1rem' }}>All third-party service providers are bound by Data Processing Agreements (DPAs) requiring GDPR-equivalent protections.</p>
          </Section>

          {/* Section 4 */}
          <Section title="4. Data Retention">
            <ul>
              <li><strong>Account Data:</strong> Retained for the duration of your subscription plus 7 years (statutory requirement)</li>
              <li><strong>Financial Records & Invoices:</strong> 7 years as required by the Companies Act, 2013</li>
              <li><strong>Session Logs & Audit Trails:</strong> 2 years for security review purposes</li>
              <li><strong>Credit Assessments:</strong> 5 years or until account deletion, whichever is earlier</li>
              <li><strong>Bank Statement Uploads:</strong> Deleted within 30 days of processing</li>
              <li><strong>Deleted Accounts:</strong> Purged within 30 days of deletion request, subject to legal retention requirements</li>
            </ul>
          </Section>

          {/* Section 5 */}
          <Section title="5. Your Rights">
            <p>Under GDPR (for EU users) and the Personal Data Protection Bill (PDPB) framework (for Indian users), you have the following rights:</p>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1rem', margin: '1rem 0' }}>
              {[
                { right: 'Right to Access', desc: 'Request a copy of all personal data we hold about you' },
                { right: 'Right to Rectification', desc: 'Correct inaccurate or incomplete personal data' },
                { right: 'Right to Erasure', desc: 'Request deletion of your data (subject to legal obligations)' },
                { right: 'Right to Portability', desc: 'Export your data in JSON or CSV format' },
                { right: 'Right to Restrict Processing', desc: 'Limit how we use your data in specific circumstances' },
                { right: 'Right to Object', desc: 'Object to processing for marketing or profiling purposes' },
              ].map((r) => (
                <div key={r.right} style={{ padding: '1rem', background: 'rgba(37,99,235,0.04)', border: '1px solid rgba(37,99,235,0.1)', borderRadius: '8px' }}>
                  <div style={{ fontWeight: 700, fontSize: '0.85rem', color: '#2563EB', marginBottom: '0.3rem' }}>{r.right}</div>
                  <div style={{ fontSize: '0.8rem', color: '#6b7280' }}>{r.desc}</div>
                </div>
              ))}
            </div>
            <p>To exercise any of these rights, contact us at <a href="mailto:privacy@proventa.in" style={{ color: '#2563EB' }}>privacy@proventa.in</a>. We will respond within 30 days.</p>
          </Section>

          {/* Section 6 */}
          <Section title="6. Security Measures">
            <p>We implement enterprise-grade security measures to protect your data:</p>
            <ul>
              <li><strong>Encryption at Rest:</strong> AES-256 encryption for all stored sensitive data</li>
              <li><strong>Encryption in Transit:</strong> TLS 1.3 for all data transmission</li>
              <li><strong>Authentication:</strong> Argon2id password hashing, database-backed session tokens with 24-hour expiry</li>
              <li><strong>Access Controls:</strong> Role-based access control (RBAC) with principle of least privilege</li>
              <li><strong>Audit Logging:</strong> All data access and modifications are logged with user identity and timestamp</li>
              <li><strong>Zero-Trust Architecture:</strong> All API endpoints require authenticated sessions; no implicit trust</li>
              <li><strong>Penetration Testing:</strong> Annual third-party security audits</li>
              <li><strong>Data Residency:</strong> Data stored in India (Mumbai region) by default</li>
            </ul>
          </Section>

          {/* Section 7 */}
          <Section title="7. Cookies & Tracking">
            <p>Proventa uses the following cookies:</p>
            <ul>
              <li><strong>Essential Cookies:</strong> Session authentication token (httpOnly, Secure, SameSite=Strict) — required for platform operation</li>
              <li><strong>Analytics Cookies:</strong> Anonymized usage analytics (opt-out available in settings)</li>
              <li><strong>Preference Cookies:</strong> Theme settings (light/dark mode) — stored client-side only</li>
            </ul>
            <p style={{ marginTop: '0.75rem' }}>We do <strong>not</strong> use third-party advertising cookies, cross-site tracking pixels, or fingerprinting technologies.</p>
          </Section>

          {/* Section 8 */}
          <Section title="8. International Data Transfers">
            <p>If you are located outside India, your data may be transferred to and processed in India where our servers are located. We ensure appropriate safeguards are in place for all cross-border transfers, including Standard Contractual Clauses (SCCs) for EU users.</p>
          </Section>

          {/* Section 9 */}
          <Section title="9. Children's Privacy">
            <p>Proventa is a B2B platform designed for businesses and professionals. We do not knowingly collect data from individuals under 18 years of age. If you believe a minor has provided us with data, contact us immediately at <a href="mailto:privacy@proventa.in" style={{ color: '#2563EB' }}>privacy@proventa.in</a>.</p>
          </Section>

          {/* Section 10 */}
          <Section title="10. Changes to This Policy">
            <p>We may update this Privacy Policy periodically. Material changes will be communicated via email and an in-platform notification at least 30 days before taking effect. Continued use of Proventa after changes constitutes acceptance of the updated policy.</p>
          </Section>

          {/* Section 11 */}
          <Section title="11. Contact & Data Protection Officer">
            <div style={{ background: '#0B1F3A', color: '#fff', padding: '1.5rem', borderRadius: '12px', lineHeight: 1.8 }}>
              <div style={{ fontFamily: 'Outfit, sans-serif', fontWeight: 700, fontSize: '1rem', marginBottom: '0.75rem' }}>Proventa Technologies Private Limited</div>
              <div style={{ fontSize: '0.875rem', color: 'rgba(255,255,255,0.8)' }}>
                <div>📧 Privacy enquiries: <a href="mailto:privacy@proventa.in" style={{ color: '#60a5fa' }}>privacy@proventa.in</a></div>
                <div>📧 General support: <a href="mailto:support@proventa.in" style={{ color: '#60a5fa' }}>support@proventa.in</a></div>
                <div style={{ marginTop: '0.5rem' }}>📍 Registered Address: [Proventa Technologies Pvt. Ltd.], India</div>
                <div>🕐 Response Time: Within 30 days for data rights requests</div>
              </div>
            </div>
          </Section>
        </div>
      </main>

      {/* Footer */}
      <footer style={{ background: '#0B1F3A', color: 'rgba(255,255,255,0.6)', padding: '2rem', textAlign: 'center', marginTop: '4rem', fontSize: '0.85rem' }}>
        <div style={{ display: 'flex', justifyContent: 'center', gap: '2rem', flexWrap: 'wrap', marginBottom: '1rem' }}>
          <Link href="/terms" style={{ color: 'rgba(255,255,255,0.7)', textDecoration: 'none' }}>Terms of Service</Link>
          <Link href="/privacy" style={{ color: '#60a5fa', textDecoration: 'none' }}>Privacy Policy</Link>
          <Link href="/book-demo" style={{ color: 'rgba(255,255,255,0.7)', textDecoration: 'none' }}>Book a Demo</Link>
        </div>
        <p style={{ margin: 0 }}>© 2025 Proventa Technologies Private Limited. All rights reserved.</p>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 style={{ fontSize: '1.2rem', fontFamily: 'Outfit, sans-serif', fontWeight: 800, color: '#0B1F3A', borderBottom: '2px solid #e2e8f0', paddingBottom: '0.5rem', marginBottom: '1rem' }}>
        {title}
      </h2>
      <div style={{ color: '#374151', lineHeight: 1.8, fontSize: '0.9rem' }}>
        {children}
      </div>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginTop: '1rem' }}>
      <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#0B1F3A', marginBottom: '0.5rem' }}>{title}</h3>
      {children}
    </div>
  );
}
